/**
 * Scans dist/client/ after a Vite build and generates src/client-manifest.ts
 * with `import ... with { type: "file" }` entries for every asset.
 *
 * These imports cause `bun build --compile` to embed the files in the binary,
 * while in source-mode they resolve to regular filesystem paths.
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, posix } from "node:path";

const ROOT = join(import.meta.dir, "..");
const DIST_DIR = join(ROOT, "dist", "client");
const SRC_DIR = join(ROOT, "src");
const OUT_FILE = join(SRC_DIR, "client-manifest.ts");

function walk(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      files.push(...walk(full));
    } else {
      files.push(full);
    }
  }
  return files;
}

const files = walk(DIST_DIR);
const imports: string[] = [];
const entries: string[] = [];

for (let i = 0; i < files.length; i++) {
  const file = files[i]!;
  // Import path relative to src/ — use posix separators for the import specifier
  const relToSrc = posix.join(
    ...relative(SRC_DIR, file).split(/[\\/]/),
  );
  // URL path the browser will request (e.g. "/index.html", "/assets/index-abc.js")
  const urlPath =
    "/" + posix.join(...relative(DIST_DIR, file).split(/[\\/]/));

  const varName = `_f${i}`;
  imports.push(`import ${varName} from "${relToSrc}" with { type: "file" };`);
  entries.push(`  ${JSON.stringify(urlPath)}: ${varName},`);
}

const content = `// Auto-generated by scripts/generate-manifest.ts — do not edit
${imports.join("\n")}

export const assets: Record<string, string> = {
${entries.join("\n")}
};
`;

writeFileSync(OUT_FILE, content);
console.log(`Generated client manifest with ${files.length} files → src/client-manifest.ts`);
